AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Lambda function to fetch value from Ssm parameter and upload in s3

Resources:
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaSsmPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                Resource: 
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${NameKey}'
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ValueKey}'
        - PolicyName: LambdaS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${S3BucketToStoreParameter}/*'
        - PolicyName: LambdaCloudWatchPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'

  ExerciseLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: !Ref LambdaHandler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref S3BucketNameForLambdaJar
        S3Key: !Ref LambdaJarName
      Runtime: java17
      Timeout: 60

Parameters:
  NameKey:
    Description: Key for the ssm parameter name.
    Type: String
    Default: Name
  ValueKey:
    Description: Key for the ssm parameter value.
    Type: String
    Default: Value
  S3BucketToStoreParameter:
    Description: S3 bucket where the SSM parameter values will be stored by Lambda function.
    Type: String
    Default: dxc-exercise-parameter
  LambdaHandler:
    Description: Lambda handler function's class qualified name::function name.
    Type: String
    Default: org.bishu.ExerciseLambda::handleRequest
  S3BucketNameForLambdaJar:
    Description: S3 bucket where lambda jar is kept.
    Type: String
    Default: dxc-assignment-lambda-jars
  LambdaJarName:
    Description: Lambda jar file name with extension
    Type: String
    Default: exercise-lambda-1.0-SNAPSHOT.jar


Outputs:
  LambdaFunctionArn:
    Description: "ARN of the Lambda Function which fetches parameter from SSM and store in S3."
    Value: !GetAtt ExerciseLambda.Arn